export const MOCK_FREELANCERS = [
  {
    id: "f1",
    name: "Alex Rivera",
    isVerified: true,
    title: "Senior Full-Stack Developer",
    category: "Web Development",
    hourlyRate: 85,
    rating: 4.9,
    reviews: 124,
    location: "Remote, US",
    completedProjects: 89,
    skills: ["React", "Node.js", "TypeScript", "Next.js", "AWS"],
    isAvailable: true,
  },
  {
    id: "f2",
    name: "Sarah Chen",
    isVerified: true,
    title: "UI/UX Product Designer",
    category: "UI/UX Design",
    hourlyRate: 65,
    rating: 5.0,
    reviews: 210,
    location: "London, UK",
    completedProjects: 156,
    skills: ["Figma", "User Research", "Prototyping", "Framer", "CSS"],
    isAvailable: true,
  },
  {
    id: "f3",
    name: "Marcus Johnson",
    isVerified: false,
    title: "Mobile App Engineer",
    category: "Mobile Apps",
    hourlyRate: 95,
    rating: 4.8,
    reviews: 67,
    location: "Austin, TX",
    completedProjects: 45,
    skills: ["React Native", "Swift", "Kotlin", "Firebase", "GraphQL"],
    isAvailable: false,
  },
  {
    id: "f4",
    name: "Elena Rodriguez",
    isVerified: true,
    title: "Growth Marketing Specialist",
    category: "Digital Marketing",
    hourlyRate: 50,
    rating: 4.7,
    reviews: 82,
    location: "Madrid, Spain",
    completedProjects: 112,
    skills: ["SEO", "Google Ads", "Content Strategy", "Analytics", "Copywriting"],
    isAvailable: true,
  },
  {
    id: "f5",
    name: "David Kim",
    isVerified: true,
    title: "Technical Writer & Documentarian",
    category: "Writing",
    hourlyRate: 45,
    rating: 4.9,
    reviews: 45,
    location: "Toronto, Canada",
    completedProjects: 60,
    skills: ["Technical Writing", "API Documentation", "Markdown", "Blogging"],
    isAvailable: true,
  },
  {
    id: "f6",
    name: "Aisha Patel",
    isVerified: false,
    title: "Frontend Developer",
    category: "Web Development",
    hourlyRate: 40,
    rating: 4.6,
    reviews: 23,
    location: "Mumbai, India",
    completedProjects: 18,
    skills: ["HTML", "CSS", "JavaScript", "React", "Tailwind"],
    isAvailable: true,
  },
  {
    id: "f7",
    name: "James Wilson",
    isVerified: true,
    title: "E-commerce Shopify Expert",
    category: "Web Development",
    hourlyRate: 75,
    rating: 4.9,
    reviews: 180,
    location: "Remote",
    completedProjects: 205,
    skills: ["Shopify", "Liquid", "E-commerce", "Stripe API"],
    isAvailable: false,
  },
  {
    id: "f8",
    name: "Chloe Dubois",
    isVerified: true,
    title: "Brand & Logo Designer",
    category: "UI/UX Design",
    hourlyRate: 55,
    rating: 4.8,
    reviews: 95,
    location: "Paris, France",
    completedProjects: 134,
    skills: ["Illustrator", "Photoshop", "Branding", "Typography"],
    isAvailable: true,
  }
];
